version: '3.8'

services:
  reservation-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    ports:
      - "5432:5432"   # udostępni port bazy na hoście (opcjonalne)
    networks:
      - reservation-net

  reservation-service:
    image: reservation-service
    depends_on:
      - reservation-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservation-db:5432/reservation_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    networks:
      - reservation-net

  users-service:
    image: users-service
    depends_on:
      - reservation-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservation-db:5432/reservation_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - reservation-net

networks:
  reservation-net:
    external: true
