apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: NodePort
  selector:
    app: users-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
