apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: weronikakoterba/users-service:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://reservation-db:5432/reservation_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: reservation-app
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
