### Dodaj nową rezerwację
POST http://localhost:8081/reservations
Content-Type: application/json

{
  "userId": 1,
  "startTime": "2025-06-01T10:00:00",
  "serviceType": "HYBRID_NAILS",
  "description": "Na urodziny"
}

###

POST http://localhost:8081/reservations
Content-Type: application/json

{
  "userId": 2,
  "startTime": "2025-06-01T10:30:00",
  "serviceType": "CLASSIC_MANICURE",
  "description": "Wzorki"
}

###

### Pobierz rezerwacje dla użytkownika 1
GET http://localhost:8081/reservations/user/1

###

### Usuń rezerwację o ID 1
DELETE http://localhost:8081/reservations/4
