### Dodaj nową rezerwację
POST http://localhost:8081/reservations
Content-Type: application/json

{
  "startTime": "2025-06-01T10:00:00",
  "serviceType": "HYBRID_NAILS",
  "description": "Na urodziny"
}

###

POST http://localhost:8081/reservations
Content-Type: application/json

{
  "price": 45,
  "startTime": "2025-06-01T10:30:00",
  "serviceType": "CLASSIC_MANICURE",
  "description": "Wzorki"
}



### 1. Rejestracja użytkownika
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "haniaa",
  "email": "hania.gibus@gmail.com",
  "password": "test123"
}

### 2. Logowanie i pobranie tokena
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "haniaa",
  "password": "test123"
}

### pobieranie dostępnych slotów
GET http://localhost:8081/reservations/available

### pobieranie slotow danego usera
GET http://localhost:8081/reservations/user/5

### rezerwacja slotu przez usera
PUT http://localhost:8081/reservations/5/bookWithPayment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYW5pYWEiLCJpYXQiOjE3NDk0MjM5ODEsImV4cCI6MTc0OTQyNzU4MX0.DZSJ8yiNDGXSLWuA8hUjJUYqIFeDl-PMlhrIjvSjeQ0

### rezygnownowanie ze slotu przez usera
PUT http://localhost:8081/reservations/5/cancel
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW5lazExMSIsImlhdCI6MTc0OTM4MDY3OSwiZXhwIjoxNzQ5Mzg0Mjc5fQ.2iX7g1kNWPLQozyK7zAeajztc8Es-8iGsPXJZxZ0OLc