apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: weronikakoterba/reservation-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://reservation-db:5432/reservation_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: reservation-app
spec:
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: ClusterIP
